name: Build and Upload PDF

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-medium
            latexmk
            lmodern
            xcolor
            pgf
            subcaption
            float
            caption
            booktabs
            longtable
            multirow
            tabularx
            listings
            algorithm2e
            mdframed
            tcolorbox
            enumitem
            hyperref
            cleveref
            import
            tocbibind
            inconsolata
            needspace
            mathtools
            bm
            amsthm
            amssymb
            amsmath

      - name: Build PDF
        run: make pdf

      - name: Prepare public directory
        run: |
          mkdir -p public
          cp ./build/main.pdf ./public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public